export const LAUNCHES_FETCH_REQUEST = "LAUNCHES_FETCH_REQUEST";
export const LAUNCHES_FETCH_SUCCESS = "LAUNCHES_FETCH_SUCCESS";
export const LAUNCHES_DROP = "LAUNCHES_DROP";
export const LAUNCHES_DROP_SUCCESS = "LAUNCHES_DROP_SUCCESS";
